# Generated by Django 5.2.6 on 2025-09-20 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quiz_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='question_preference',
            field=models.CharField(choices=[('SHORT', 'Short Questions'), ('TF', 'True/False'), ('MCQ', 'Multiple Choice'), ('FILL', 'Fill in the Blank'), ('MIX', 'Mix')], default='MIX', max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
