# Generated by Django 5.2.6 on 2025-09-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quiz_question_preference_alter_quiz_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
    ]
