# Generated by Django 5.2.6 on 2025-10-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_server_serverquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='light_mode',
            field=models.BooleanField(default=False),
        ),
    ]
