from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.handle_login, name='login'),
    path('signup/', views.handle_signup, name='signup'),
    path('main/', views.main, name='main'),
    path('generate_quiz/', views.generate_quiz, name='generate_quiz'),
    path('all_quizes/', views.all_quizes, name='all_quizes'),
    path("quiz_detail/<int:quiz_id>/", views.quiz_detail, name="quiz_detail"),
    path("quiz/<int:quiz_id>/", views.quiz_take, name="quiz_take"),
    path("quiz/result/<int:attempt_id>/", views.quiz_result, name="quiz_result"),
    path('logout/', views.handle_logout, name='logout'),
    path('delete_quiz/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),
    path("quiz/<int:quiz_id>/share/", views.share_quiz, name="share_quiz"),
    path('retake_quiz/<int:quiz_id>/', views.retake_quiz, name='retake_quiz'),
    path('settings/', views.settings, name='settings'),
    path("quiz/<int:quiz_id>/is-public/", views.is_public, name="is_public"),
    path('change_password/', views.change_password, name='change_password'),
    path("chat-assistant/", views.chat_assistant, name="chat_assistant"),
    path("change-profile/", views.change_username_or_email, name="change_username_or_email"),
    path("profile/", views.profile, name="profile"),
    path("delete_account/", views.delete_account, name="delete_account"),
    path("quiz/<int:quiz_id>/rate/", views.rate_quiz, name="rate_quiz"),
    path("explore/", views.explore, name="explore"),
    path("add_to_my_quiz/<int:quiz_id>/", views.add_to_my_quiz, name="add_to_my_quiz"),
    path('servers/', views.server_list, name='server_list'),
    path('servers/create/', views.create_server, name='create_server'),
    path('servers/join/', views.join_server, name='join_server'),
    path('servers/<int:server_id>/', views.server_detail, name='server_detail'),
    path("server/<int:server_id>/add-quiz/", views.add_quiz_to_server, name="add_quiz_to_server"),
    path("servers/<int:server_id>/delete/", views.delete_server, name="delete_server"),
    path("servers/<int:server_id>/members/", views.show_members, name="show_members"),
    path("show_server_quiz_results/<int:server_id>/", views.show_server_quiz_results, name="show_server_quiz_results"),
]
